version: '3'

services:
  postgres:
    image: postgres:13
    container_name: link-shortener-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    container_name: link-shortener-django
    build:
      context: ./shortener_backend
    volumes:
      - ./shortener_backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  vue:
    container_name: link-shortener-vue
    build:
      context: ./shortener_frontend
    volumes:
      - ./shortener_frontend/.env:/app/.env
      - ./shortener_frontend/.eslintrc.js:/app/.eslintrc.js
      - ./shortener_frontend/.prettierrc.json:/app/.prettierrc.json
      - ./shortener_frontend/index.html:/app/index.html
      - ./shortener_frontend/package.json:/app/package.json
      - ./shortener_frontend/package-lock.json:/app/package-lock.json
      - ./shortener_frontend/src:/app/src
      - ./shortener_frontend/vite.config.js:/app/vite.config.js
    ports:
      - "5173:5173"
    depends_on:
      - django

volumes:
  postgres_data: