# Generated by Django 5.0.2 on 2024-03-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='original_url',
            field=models.URLField(max_length=500),
        ),
    ]
